import JSZip from 'jszip';

/**
 * Creates and downloads a ready-to-test ZIP package containing
 * frontend (Vite + React) and backend (Express) folder structures.
 * 
 * @param {Object} codeData - Object containing appJsx, serverRoutes, and components
 * @param {string} [projectName='generated-app'] - Name of the project archive
 */
export async function downloadProjectZip(codeData, projectName = 'generated-app') {
    if (!codeData) return;

    const zip = new JSZip();
    const safeProjectName = (projectName || 'generated-app')
        .toLowerCase()
        .replace(/[^a-z0-9-_]/g, '-')
        .replace(/-+/g, '-');

    const rootFolder = zip.folder(safeProjectName);

    // ==========================================
    // 1. Root README.md & Instructions
    // ==========================================
    const rootReadme = `# ${projectName || 'Generated App'}

Generated with DevEngine AI.

## Quick Start (Run Locally)

### 1. Start the Backend
\`\`\`bash
cd backend
npm install
npm run dev
\`\`\`
The backend API server will run on **http://localhost:5000**.

### 2. Start the Frontend
\`\`\`bash
cd frontend
npm install
npm run dev
\`\`\`
The React web application will start on **http://localhost:5173**.
`;
    rootFolder.file('README.md', rootReadme);

    // ==========================================
    // 2. Backend Files
    // ==========================================
    const backendFolder = rootFolder.folder('backend');

    const backendPackageJson = {
        name: `${safeProjectName}-backend`,
        version: "1.0.0",
        description: "Express backend generated by DevEngine",
        main: "server.js",
        scripts: {
            start: "node server.js",
            dev: "nodemon server.js"
        },
        dependencies: {
            express: "^4.19.2",
            cors: "^2.8.5",
            dotenv: "^16.4.5"
        },
        devDependencies: {
            nodemon: "^3.1.0"
        }
    };
    backendFolder.file('package.json', JSON.stringify(backendPackageJson, null, 2));
    backendFolder.file('.env.example', 'PORT=5000\n');
    backendFolder.file('.gitignore', 'node_modules\n.env\n');

    const backendServerJs = `const express = require('express');
const cors = require('cors');
require('dotenv').config();

const apiRoutes = require('./routes/api');

const app = express();
const PORT = process.env.PORT || 5000;

app.use(cors());
app.use(express.json());

// Routes
app.use('/api', apiRoutes);

// Health check
app.get('/health', (req, res) => {
    res.json({ status: 'ok', time: new Date() });
});

app.listen(PORT, () => {
    console.log(\`Backend server running at http://localhost:\${PORT}\`);
});
`;
    backendFolder.file('server.js', backendServerJs);

    const routesFolder = backendFolder.folder('routes');
    routesFolder.file('api.js', codeData.serverRoutes || '// Express API Routes\nconst express = require("express");\nconst router = express.Router();\n\nmodule.exports = router;\n');

    // ==========================================
    // 3. Frontend Files
    // ==========================================
    const frontendFolder = rootFolder.folder('frontend');

    const frontendPackageJson = {
        name: `${safeProjectName}-frontend`,
        private: true,
        version: "1.0.0",
        type: "module",
        scripts: {
            dev: "vite",
            build: "vite build",
            preview: "vite preview"
        },
        dependencies: {
            react: "^18.3.1",
            "react-dom": "^18.3.1",
            "lucide-react": "^0.475.0",
            axios: "^1.7.9"
        },
        devDependencies: {
            "@vitejs/plugin-react": "^4.3.4",
            autoprefixer: "^10.4.20",
            postcss: "^8.4.49",
            tailwindcss: "^3.4.17",
            vite: "^6.0.0"
        }
    };
    frontendFolder.file('package.json', JSON.stringify(frontendPackageJson, null, 2));

    frontendFolder.file('vite.config.js', `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  server: {
    port: 5173
  }
});
`);

    frontendFolder.file('tailwind.config.js', `/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
`);

    frontendFolder.file('postcss.config.js', `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
`);

    frontendFolder.file('index.html', `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${projectName || 'Generated App'}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
`);

    frontendFolder.file('.gitignore', 'node_modules\ndist\n.env\n');

    const srcFolder = frontendFolder.folder('src');

    srcFolder.file('main.jsx', `import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App.jsx';
import './index.css';

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);
`);

    srcFolder.file('index.css', `@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Fira Sans', 'Droid Sans', 'Helvetica Neue', sans-serif;
  -webkit-font-smoothing: antialiased;
}
`);

    // App.jsx
    srcFolder.file('App.jsx', codeData.appJsx || `export default function App() {\n  return <div><h1>Welcome to ${projectName}</h1></div>;\n}`);

    // Components subfolder
    if (codeData.components && typeof codeData.components === 'object') {
        const componentsFolder = srcFolder.folder('components');
        for (const [name, code] of Object.entries(codeData.components)) {
            const fileName = name.endsWith('.jsx') || name.endsWith('.js') ? name : `${name}.jsx`;
            componentsFolder.file(fileName, code);
        }
    }

    // ==========================================
    // 4. Generate Blob & Trigger Download
    // ==========================================
    const content = await zip.generateAsync({ type: 'blob' });
    const downloadUrl = URL.createObjectURL(content);

    const link = document.createElement('a');
    link.href = downloadUrl;
    link.download = `${safeProjectName}.zip`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(downloadUrl);
}
